name: Package Publish
  
on: 
  push:
    tags:
    - '*'
  
jobs:
  public_packages:
  
    runs-on: windows-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
    - name: Display version information
      run: |
       echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
       echo "BranchName: ${{ steps.gitversion.outputs.branchName }}"

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build Changelog
      id: github_release
      with:
        commitMode: true
        configuration: ".github/configuration_commits.json"
      uses: mikepenz/release-changelog-builder-action@v3.7.2
      env:
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}

    - name: Pack romaklayt.DynamicFilter.Binder.Net
      run: dotnet pack src/romaklayt.DynamicFilter.Binder.Net/romaklayt.DynamicFilter.Binder.Net.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} 
    
    - name: Pack romaklayt.DynamicFilter.Common
      run: dotnet pack src/romaklayt.DynamicFilter.Common/romaklayt.DynamicFilter.Common.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} 
    
    - name: Pack romaklayt.DynamicFilter.Extensions.EntityFrameworkCore
      run: dotnet pack src/romaklayt.DynamicFilter.Extensions.EntityFrameworkCore/romaklayt.DynamicFilter.Extensions.EntityFrameworkCore.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} 

    - name: Pack romaklayt.DynamicFilter.Extensions.EntityFramework
      run: dotnet pack src/romaklayt.DynamicFilter.Extensions.EntityFramework/romaklayt.DynamicFilter.Extensions.EntityFramework.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} 

    - name: Pack romaklayt.DynamicFilter.Extensions.Async
      run: dotnet pack src/romaklayt.DynamicFilter.Extensions.Async/romaklayt.DynamicFilter.Extensions.Async.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} 
    
    - name: Pack romaklayt.DynamicFilter.Parser
      run: dotnet pack src/romaklayt.DynamicFilter.Parser/romaklayt.DynamicFilter.Parser.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} 
    
    - name: Pack romaklayt.DynamicFilter.Binder.NetFramework.Mvc
      run: dotnet pack src/romaklayt.DynamicFilter.Binder.NetFramework.Mvc/romaklayt.DynamicFilter.Binder.NetFramework.Mvc.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} 
    
    - name: Pack romaklayt.DynamicFilter.Binder.NetFramework.WebApi
      run: dotnet pack src/romaklayt.DynamicFilter.Binder.NetFramework.WebApi/romaklayt.DynamicFilter.Binder.NetFramework.WebApi.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} 
    
    - name: Push to nuget
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      working-directory: nuget-packages

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.github_release.outputs.changelog }}
        token: ${{ secrets._GITHUB_TOKEN }}