name: Build Projects
  
on:
  push:
    branches:
      - master
      - develop
    tags:
    - '*'
  pull_request:
  
jobs:
  build_libraries:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
  
    name: build packages on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v2.0.0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v2.0.0
    - name: Display version information
      run: |
       echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
       echo "BranchName: ${{ steps.gitversion.outputs.branchName }}"

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore romaklayt.DynamicFilter.sln

    - name: Build romaklayt.DynamicFilter.Binder.Net
      run: dotnet build src/romaklayt.DynamicFilter.Binder.Net/romaklayt.DynamicFilter.Binder.Net.csproj --configuration Release --no-restore

    - name: Build romaklayt.DynamicFilter.Common
      run: dotnet build src/romaklayt.DynamicFilter.Common/romaklayt.DynamicFilter.Common.csproj --configuration Release --no-restore

    - name: Build romaklayt.DynamicFilter.Extensions.EntityFrameworkCore
      run: dotnet build src/romaklayt.DynamicFilter.Extensions.EntityFrameworkCore/romaklayt.DynamicFilter.Extensions.EntityFrameworkCore.csproj --configuration Release --no-restore

    - name: Build romaklayt.DynamicFilter.Extensions.Async
      run: dotnet build src/romaklayt.DynamicFilter.Extensions.Async/romaklayt.DynamicFilter.Extensions.Async.csproj --configuration Release --no-restore

    - name: Build romaklayt.DynamicFilter.Parser
      run: dotnet build src/romaklayt.DynamicFilter.Parser/romaklayt.DynamicFilter.Parser.csproj --configuration Release --no-restore

  build-test-dotnet-api:
  
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
  
    name: build test dotnet api on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v2.0.0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v2.0.0
    - name: Display version information
      run: |
       echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
       echo "BranchName: ${{ steps.gitversion.outputs.branchName }}"
       
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore romaklayt.DynamicFilter.sln

    - name: Build romaklayt.DynamicFilter.Test.Api
      run: dotnet build test/romaklayt.DynamicFilter.Test.Api/romaklayt.DynamicFilter.Test.Api.csproj --configuration Release --no-restore