name: Build Projects
  
on:
  push:
    branches:
      - master
      - develop
      - hotfix/*
      - feature/*
      - release/*
  pull_request:
    branches: 
      - master
      - develop
      - hotfix/*
      - feature/*
      - release/*
  
jobs:
  build_libraries:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
  
    name: build packages on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Display version information
      run: |
       echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
       echo "BranchName: ${{ steps.gitversion.outputs.branchName }}"

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore romaklayt.DynamicFilter.sln

    - name: Build romaklayt.DynamicFilter.Binder.Net
      run: dotnet build src/romaklayt.DynamicFilter.Binder.Net/romaklayt.DynamicFilter.Binder.Net.csproj --configuration Release --no-restore

    - name: Build romaklayt.DynamicFilter.Binder.NetFramework.Mvc
      run: dotnet build src/romaklayt.DynamicFilter.Binder.NetFramework.Mvc/romaklayt.DynamicFilter.Binder.NetFramework.Mvc.csproj --configuration Release --no-restore

    - name: Build romaklayt.DynamicFilter.Binder.NetFramework.WebApi
      run: dotnet build src/romaklayt.DynamicFilter.Binder.NetFramework.WebApi/romaklayt.DynamicFilter.Binder.NetFramework.WebApi.csproj --configuration Release --no-restore

    - name: Build romaklayt.DynamicFilter.Common
      run: dotnet build src/romaklayt.DynamicFilter.Common/romaklayt.DynamicFilter.Common.csproj --configuration Release --no-restore

    - name: Build romaklayt.DynamicFilter.Extensions
      run: dotnet build src/romaklayt.DynamicFilter.Extensions/romaklayt.DynamicFilter.Extensions.csproj --configuration Release --no-restore

    - name: Build romaklayt.DynamicFilter.Extensions.Async
      run: dotnet build src/romaklayt.DynamicFilter.Extensions.Async/romaklayt.DynamicFilter.Extensions.Async.csproj --configuration Release --no-restore

    - name: Build romaklayt.DynamicFilter.Parser
      run: dotnet build src/romaklayt.DynamicFilter.Parser/romaklayt.DynamicFilter.Parser.csproj --configuration Release --no-restore

  build-test-dotnet-api:
  
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
  
    name: build test dotnet api on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Display version information
      run: |
       echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
       echo "BranchName: ${{ steps.gitversion.outputs.branchName }}"
       
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore romaklayt.DynamicFilter.sln

    - name: Build romaklayt.DynamicFilter.Test.Api
      run: dotnet build test/romaklayt.DynamicFilter.Test.Api/romaklayt.DynamicFilter.Test.Api.csproj --configuration Release --no-restore

  build-test-netframework-api:
 
    runs-on: windows-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Display version information
      run: |
       echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
       echo "BranchName: ${{ steps.gitversion.outputs.branchName }}"
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.3
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
     
    - name: Restore NuGet Packages
      run: nuget restore romaklayt.DynamicFilter.sln
 
    - name: Build and Publish Web App
      run: msbuild test/romaklayt.DynamicFilter.Test.Api.NetFramework/romaklayt.DynamicFilter.Test.Api.NetFramework.csproj /p:Configuration=Release